<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>acceptCookies</name>
   <tag></tag>
   <elementGuidId>95024e6f-702a-41a8-a159-94d414cf5cbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[normalize-space()='Mengerti!']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//a[normalize-space()='Mengerti!']</value>
      <webElementGuid>6b744ca4-1a6d-4315-8cf3-92afd1f4d2cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
