<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>passwordForm</name>
   <tag></tag>
   <elementGuidId>5853ec51-44ec-40ca-9634-088ee70ccae2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id='password']</value>
      <webElementGuid>dfa57497-bd62-4419-b3a3-e674180db6b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
