<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>usernameForm</name>
   <tag></tag>
   <elementGuidId>548c63b1-938c-43dd-9f31-dc2005ad0ff3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='username']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id='username']</value>
      <webElementGuid>61347681-bfae-4813-b888-2a5a2122f9e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
