<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confrimPasswordForm</name>
   <tag></tag>
   <elementGuidId>2eb2097e-871b-43bb-8717-6e824b7d959e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirm_password']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id='confirm_password']</value>
      <webElementGuid>f1816e1b-88ea-4d7c-b288-6051f00974b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
