<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailForm</name>
   <tag></tag>
   <elementGuidId>3a1f5baf-b692-42ee-a91c-215103479139</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id='email']</value>
      <webElementGuid>0cdf7429-fbef-43c0-8aa3-cf54fb5b3774</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
