<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firstNameForm</name>
   <tag></tag>
   <elementGuidId>afbe66f8-6783-4e55-b0e1-8d32c2ca7b7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='first_name']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id='first_name']</value>
      <webElementGuid>dad3ae66-4264-4526-af69-869cb2bc3c5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
