<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lastNameForm</name>
   <tag></tag>
   <elementGuidId>175916e4-d569-4dcd-8451-1778d400f58b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='last_name']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id='last_name']</value>
      <webElementGuid>c2414b55-7a1b-4751-9ef8-7fd6f42d161a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
